### ISSUE TITLE
Captions wont re-save

### ISSUE THREAD

**Issue by mackski** [justonestep/processwire-imageextra#1]
Entering captions for the first time work, then re-saving the page clears all captions, and new ones are not saved.

Here is a quick fix:
1045: $value = $this->wire('sanitizer')->entities($language ? $pagefile->{$current}($language) : $pagefile->{$current});

**Comment by justonestep** [comment]
I cannot reproduce this behavior. Could you please provide me more informations:

* ProcessWire Version
* Number of max allowed files
* Overwrite existing files?
* Do you just change meta informations or upload a new image?
* Do you use ImageExtra in combination with any other Image Module? (Please tell me which one)

I installed a fresh ProcessWire installation, Beginner Package (just one language), and it works without any problems.

**Comment by mackski** [comment]
PW: 2.5.3
Max files 1
Overwrite: true
Just change Meta
Not in combination

Further it appears the data is saved within the database correctly, just not rendered upon page load.

**Comment by justonestep** [comment]
Thanks, I still cannot reproduce this behavior but your fix looks good. I added it to the master branch.

**Comment by mackski** [comment]
Forgive my ignorance, while i understand {$current} is dynamic, what does the appended ($language) do part actually do?

**Comment by justonestep** [comment]
``Current`` just include a fieldname. ``Current`` could be _caption_ or any other value you entered in _otherField_. If you just have one language, you need only the fieldname to get the value. For each other language you need to transfer the language as a param to get a language specific value. Have a look at line 264, the first argument is ``language`` and depending on that there are different switches. Or have a look at the core file "wire/core/Pagefile.php" line 206 function description - this is the same as the hook mentioned above. I couldn't use determined names because the entry in otherField is dynamic.
