### ISSUE TITLE
Limit "Select the inputfields where the extra fields should be attached" to appropriate types

### ISSUE THREAD

**Issue by adrianbj** [justonestep/processwire-imageextra#11]
I think it would be nicer if only inputfields relevant to images (and perhaps fields if they worked) were listed, rather than all inputfield types.

**Comment by justonestep** [comment]
I agree but I have no idea how to achieve this. At the moment I loop over all modules, grep all with the word `Inputfield`. All I now about a module is: autoload, singular and file. I could exclude all known modules (long, long list) to minimize the list, but there will be some custom modules I don't recognized as well as new ones.

**Comment by adrianbj** [comment]
Instead of what you have:
```
foreach (wire('modules') as $module) {
    if (preg_match('/^Inputfield/', $module)) {
         $field->addOption($module->name, $module->name);
    }
}
```
Do this instead: 
```
foreach(wire('fields') as $fieldoption) {
     // filter out incompatible field types
     if($fieldoption->type instanceof FieldtypeImage)  $f->addOption($fieldoption->name);
 }
```

**Comment by justonestep** [comment]
Nope, this doesn't work, custom fieldtypes like _CroppableImage_ are missing and the name is just "images" but I need "InputfieldImage".

**Comment by adrianbj** [comment]
Sorry, my mistake, try this:
```
    foreach(wire('fields') as $fieldoption) {
      if($fieldoption->type instanceof FieldtypeImage)  $field->addOption($fieldoption->inputfieldClass);
    }
```
That gets me InputfieldImage, InputfieldCropImage, and InputfieldCroppableImage so it think it should do what you need.

However, I personally wonder whether it would be better to limit by the field names. I don't actually want ImageExtra applied to all fields of a particular InputfieldType. I usually want to limit it to just specific fields. The first approach I listed above would allow that, but obviously you would need to tweak:
```
$fieldNameFields = wire('fields')->find('inputfieldClass=' . implode('|', $this->selectedInputfields));
```
to get the fields via selected names, rather than inputfieldtypes.

Hope that helps.

**Comment by adrianbj** [comment]
PS My first approach returns CroppableImage fields for me

**Comment by justonestep** [comment]
My fault. I didn't get you right. You want to change the list from general inputfield types to specific existing fields. For that scenario your first approach will work for sure. I thought the goal is to limit the list of inputfield types so it only displays "InputfieldImage" and "InputfieldCroppableImage" as option for example. 

Some questions on this. Why do you want to change this behaviour? If I add the optional extra fields for all InputfieldImage fields there are probably some fields which won't need them. But it doesn't bother me because it's just an collapsed fieldset which doesn't effect the field if I keep the fields empty. On the other side it would annoy me if I had to go to the ImageExtra module settings every time after I created a new image field where I want the extra fields to be attached.

One idea is to combine both approaches. So every user can decide on his own whether to use the inputfield type approach or the single field one. I would combine them in an OR way. Doing it this way means also that an update of the module doesn't break anything.

What do you think?

**Comment by adrianbj** [comment]
You're probably right - it's only a couple of extra lines in the db table for each of the image fields and a collapsed fieldset.

I am just trying to make your module look cleaner - it's weird that currently you can select "InputfieldDateTime" for example - that just doesn't make any sense.

I would at least go for:

```
    foreach(wire('fields') as $fieldoption) {
      if($fieldoption->type instanceof FieldtypeImage)  $field->addOption($fieldoption->inputfieldClass);
    }
```

But then again, if you don't think it matters having the ImageExtra collapsed fieldset on the Input tab of all Image fields, then why even give users an option here - why not just add it to all image related inputfields?

Anyway, not a big deal for me either way :)

**Comment by justonestep** [comment]
I'm completely with you to limit the list of available inputs because most of them doesn't make any sense.

The problem is, how do I get all available / installed modules which are an instance of FieldtypeImage. If I use your approach I just get the inputfield types for which a field already exists. If I've installed CroppableImage and didn't create a field of this type so far, CroppableImage woudn't be listed there. Maybe this is just an edge case... 

But you're right, maybe it would be the best to remove the module settings and add it to all related inputfields...

**Comment by adrianbj** [comment]
Ah - yes, I didn't think about wire('fields') not working if there isn't already a field defined with the Inputfield type. 

Anyway, it's not a huge deal, so will bow out now and leave it to your best judgement.

**Comment by justonestep** [comment]
The extra fields (collapsed fieldset) will be added to all related fields (instances of FieldtypeImage) by default. It's no longer required to add the inputfields manually. Thanks!
