### ISSUE TITLE
Allowing markdown in the fields

### ISSUE THREAD

**Issue by formmailer** [justonestep/processwire-imageextra#4]
Hi!

It would be great if using markdown in the extra fields would be possible.
Adding a checkbox to allow Markdown would be an option.

Thanks!

**Comment by justonestep** [comment]
Hi,
it took some time but now it's possible to use a textformatter e.g. markdown parser. This is only available in branch develop for PW3.x.

There is a little issue due to focus textareas, I created a [PR](https://github.com/ryancramerdesign/ProcessWire/pull/1857) to solve this.

How to use it: go to field settings, enter some other fields, save. Reopen ImageExtra tab, now you can see a table below in which you can define one textformatter for each extra field. All installed text formatters will be listet in this dropdown.

![formatters](https://cloud.githubusercontent.com/assets/4669205/15740317/b2d0c5c4-28b4-11e6-9a92-851e3c3dfab5.png)
